//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoreboardWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameResults
    {
        public int ID { get; set; }
        public string Sport { get; set; }
        public string HomeTeamName { get; set; }
        public int HomeTeamScore { get; set; }
        public string VisitorTeamName { get; set; }
        public int VisitorTeamScore { get; set; }
        public string Period { get; set; }
    }
}
